
import type { Metadata } from "next";

import { Provider } from "@/components/ui/provider"
import { ReactNode } from "react";

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
  );
};